### ISSUE TITLE
Add ability to return translator (docchi)

### ISSUE THREAD

**Issue by ppogorze** [docchipl/Pobieranie-anime-z-polskich-stron#20]
I want to scrape only for videos which are not translated by ai. Is it possible?

**Comment by anKordii** [comment]
Yes, feature will be added in future update ;)

**Comment by anKordii** [comment]
Released https://www.npmjs.com/package/@docchi/scraping-anime-websites-poland/v/1.0.44

**Comment by ppogorze** [comment]
Wow, that was fast. Thanks a lot! <3
